name: .NET

on: [push, pull_request]

env:
  EXCLUDE_RUN_ID_FROM_PACKAGE: false
  EXCLUDE_SUFFIX_FROM_VERSION: false

jobs:

  # Build the whole ComputeSharp solution, in Debug
  build-solution-debug:
    runs-on: windows-2022
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: msbuild -t:restore,build /p:Configuration=Debug /p:Platform=x64 /bl
      shell: cmd
    - name: Upload MSBuild binary log
      uses: actions/upload-artifact@v2
      with:
        name: msbuild_log
        path: msbuild.binlog
        if-no-files-found: error

  # Build the whole ComputeSharp solution, in Release
  build-solution-release:
    runs-on: windows-2022
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: msbuild -t:restore,build /p:Configuration=Release /p:Platform=x64
      shell: cmd

  # Build the .msbuildproj projects and the UWP/WinUI projects to generate all the NuGet packages.
  # This workflow also uploads the resulting packages as artifacts.
  build-packages:
    runs-on: windows-2022
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build ComputeSharp.Core package
      run: dotnet build src\ComputeSharp.Core.Package\ComputeSharp.Core.Package.msbuildproj -c Release
      shell: cmd
    - name: Build ComputeSharp package
      run: dotnet build src\ComputeSharp.Package\ComputeSharp.Package.msbuildproj -c Release
      shell: cmd
    - name: Build ComputeSharp.Dynamic package
      run: dotnet build src\ComputeSharp.Dynamic.Package\ComputeSharp.Dynamic.Package.msbuildproj -c Release
      shell: cmd
    - name: Build ComputeSharp.D2D1 package
      run: dotnet build src\ComputeSharp.D2D1.Package\ComputeSharp.D2D1.Package.msbuildproj -c Release
      shell: cmd
    - name: Build ComputeSharp.Uwp package
      run: msbuild src\ComputeSharp.Uwp\ComputeSharp.Uwp.csproj -t:restore,build,pack /p:Configuration=Release
      shell: cmd
    - name: Restore ComputeSharp.WinUI project
      run: msbuild src\ComputeSharp.WinUI\ComputeSharp.WinUI.csproj -t:restore /p:Configuration=Release
      shell: cmd
    - name: Build ComputeSharp.WinUI package
      run: msbuild src\ComputeSharp.WinUI\ComputeSharp.WinUI.csproj -t:pack /p:Configuration=Release
      shell: cmd # Packing needs to be done separately and with no previous build target for it to work correctly
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget_preview
        path: artifacts\*.nupkg
        if-no-files-found: error

  # Download the NuGet packages generated in the previous job and use them
  # to build and run the sample project referencing them. This is used as
  # a test to ensure the NuGet packages work in a consuming project.
  verify-packages:
    if: success()
    needs: [build-packages]
    runs-on: windows-2022
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Create local NuGet feed
      run: mkdir artifacts
      shell: cmd
    - name: Download package artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget_preview
        path: artifacts
    - name: Build ComputeSharp.Sample.NuGet (.NET 6)
      run: dotnet build samples\ComputeSharp.Sample.NuGet\ComputeSharp.Sample.NuGet.csproj -c Release -f net6.0
      shell: cmd
    - name: Run ComputeSharp.Sample.NuGet (.NET 6)
      run: dotnet samples\ComputeSharp.Sample.NuGet\bin\Release\net6.0\ComputeSharp.Sample.NuGet.dll
      shell: cmd
    - name: Build ComputeSharp.Sample.NuGet (.NET Core 3.1)
      run: dotnet build samples\ComputeSharp.Sample.NuGet\ComputeSharp.Sample.NuGet.csproj -c Release -f netcoreapp3.1 -r win-x64
      shell: cmd
    - name: Run ComputeSharp.Sample.NuGet (.NET Core 3.1)
      run: samples\ComputeSharp.Sample.NuGet\bin\Release\netcoreapp3.1\win-x64\ComputeSharp.Sample.NuGet.exe
      shell: cmd
    - name: Build ComputeSharp.Sample.NuGet (.NET Framework 4.7.2)
      run: dotnet build samples\ComputeSharp.Sample.NuGet\ComputeSharp.Sample.NuGet.csproj -c Release -f net472 /p:Platform=x64
      shell: cmd
    - name: Run ComputeSharp.Sample.NuGet (.NET Framework 4.7.2)
      run: samples\ComputeSharp.Sample.NuGet\bin\x64\Release\net472\ComputeSharp.Sample.NuGet.exe
      shell: cmd


  # Publish the packages to GitHub packages
  publish-nightlies-github:
    needs: [ verify-packages ]
    runs-on: windows-2022
    if: ${{github.event_name == 'push'}}
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: nuget_preview
        path: artifacts
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet nuget push "artifacts\*.nupkg" --source "https://nuget.pkg.github.com/Shmuelie.WinRTServer/index.json" --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
      shell: cmd
